# -*- coding: utf-8 -*-
"""Salários

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-P41OPZ4Z3LAgK3C420pLF1tA_s8hTfY

**Análise de Dados com Python**
"""

#Importando as bibliotecas 
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("seaborn")

df = pd.read_csv("/content/drive/MyDrive/DADOS/Python/salarios1.csv")

#Vizualizando as 5 primeiras linhas
df.head()

#Quantidade de linhas e colunas
df.shape

# Renomeando as colunas
df = df.rename(columns={"Name":"Nome", "Position Title": "Cargo", "Department":"Departamento", "Employee Annual Salary":"Salário Anual"})

#Verificando os tipos de dados
df.dtypes

#Qual a média salárial?
df["Salário Anual"].mean()

# Informações vazia
# Colunas completamente vazias -> excluir
df = df.dropna(how='all', axis=1)

# Linhas q tem alguma informação vazia
df = df.dropna(how='any', axis=0)

print(df.info())

#Retornando o maior salário
df["Salário Anual"].max()

#Retornando o menor salário
df["Salário Anual"].min()

#Agrupamento por Departamento
df.groupby("Departamento")["Salário Anual"].sum()

#Gráfico Total dos salários
df.groupby("Departamento")["Salário Anual"].sum().sort_values(ascending=True).plot.barh(title="Salário Anual por Departamento")
plt.xlabel("Total")
plt.ylabel("Departamento");

#Gráfico de Boxplot
plt.boxplot(df["Salário Anual"]);